### ISSUE TITLE
Does the API still work (as of yesterday server upgrade)?

### ISSUE THREAD

**Issue by JackDinn** [DiaKEM/libre-link-up-api-client#24]
Hi,

I use info i have found from around the github to build my own API access and an app that has become critical to my condition management. 
It look to be very similar to yours. in the way it accesses the LinkUp API

However, as of last night, after the Libre servers when down for a while and were updated I have not been able to connect to the API any more.

Can you tell me if you are aware of any API changes?
it's possible that the API endpoint or required headers have changed. The API might now expect different headers, a different version number, or even a different authentication method.

But all i get now is 
`Fetching connections failed: 401 Client Error: Unauthorized for url: https://api-eu2.libreview.io/llu/connections`

But the credentials are fine on a android phone with Librelinkup app installed and they have been working fine with this script for more than a year now. I have changed nothing.

Im almost 100% sure something has changed at their end.

I tried changing the 'version': '4.7.0' in the header to 4.8.0, 4.8.0, 4.9.0 & 4.10.0 but still the same output.

Does your script still work? (i cant figure how to install it to test with, but i suspect it will give the same error).

I have attached my API script.

Please help, thx.

```
#!/home/greg/PycharmProjects/sugarpixel/.venv2/bin/python

import requests
import json
import time
import os
from datetime import datetime

BASE_URL = 'https://api-eu2.libreview.io'
HEADERS = {
    'accept-encoding': 'gzip',
    'cache-control': 'no-cache',
    'connection': 'Keep-Alive',
    'content-type': 'application/json',
    'product': 'llu.android',
    'version': '4.7.0',
}

TOKEN_FILE = 'api_token.json'


def save_token_to_file(token, expiry):
    with open(TOKEN_FILE, 'w') as file:
        json.dump({'token': token, 'expiry': expiry}, file)


def load_token_from_file():
    if os.path.exists(TOKEN_FILE):
        with open(TOKEN_FILE, 'r') as file:
            data = json.load(file)
            if data['expiry'] > time.time():
                return data['token']
    return None


def login(email, password):
    url = f"{BASE_URL}/llu/auth/login"
    payload = {"email": email, "password": password}
    try:
        response = requests.post(url, headers=HEADERS, json=payload)
        response.raise_for_status()  # Checks HTTP status codes for errors
        data = response.json()
        token = data['data']['authTicket']['token']
        expiry = time.time() + 9600  # Assuming the token is valid for 1 hour
        save_token_to_file(token, expiry)
        print("creating new token")
        return token
    except requests.RequestException as e:
        print(f"Login request failed: {e}")
        return False
    except KeyError:
        print("Unexpected response format during login")
        return False


def get_connections(token):
    url = f"{BASE_URL}/llu/connections"
    headers = {**HEADERS, 'authorization': f'Bearer {token}'}
    try:
        response = requests.get(url, headers=headers)
        response.raise_for_status()
        connections = response.json()
        if connections['status'] == 0 and connections['data']:
            return connections['data']
        else:
            print("No connections data found or status not zero")
            return False
    except requests.RequestException as e:
        print(f"Fetching connections failed: {e}")
        return False


def get_cgm_data(token, patient_id):
    url = f"{BASE_URL}/llu/connections/{patient_id}/graph"
    headers = {**HEADERS, 'authorization': f'Bearer {token}'}
    try:
        response = requests.get(url, headers=headers)
        response.raise_for_status()
        return response.json()
    except requests.RequestException as e:
        raise SystemExit(f"Fetching CGM data failed: {e}")


def main():
    token = load_token_from_file()
    if not token:
        email = "myemail@email.co.uk"
        password = "password"
        token = login(email, password)
        if not token:
            return False
    try:
        connections_data = get_connections(token)
        if not connections_data:
            return False
        patient_id = connections_data[0]['patientId']  # Assume the first patient
        cgm_data = get_cgm_data(token, patient_id)
        outx = cgm_data
        print(f"{datetime.now()}  using token")
    except Exception as e:
        outx = f"An error occurred: {e}"
        print(f"An error occurred: {e}")
    return outx


if __name__ == "__main__":
    out = main()
    print(json.dumps(out, indent=4))  # Pretty print the CGM data
```

> Fetching connections failed: 401 Client Error: Unauthorized for url: https://api-eu2.libreview.io/llu/connections

**Comment by JackDinn** [comment]
Ok i have been able to install your script but it is giving the same error,  

Snipet of output:
```
statusCode: 401,
      statusMessage: 'Unauthorized',
      client: [TLSSocket],
```

I know 100% that my credentials work as i am using them in both an android phone with Librelinkup and a SugarPixel device, they are both connecting fine to this same account.

**Comment by khskekec** [comment]
Just tested it now and it looks fine with the client.

**Comment by marcbarry** [comment]
Same, I seeing getting 401 replies back from the API at around 23:30~ UK time on Tuesday (24th Sept).

**Comment by marcbarry** [comment]
Mystery solved... They've updated their terms.

You need to logout of all of devices and then log back in again using the LibreLinkUp mobile app in order for you to be presented with an option to accept the new terms.

Once accepted, the `401` responses from the API should go away. Using `clientVersion: 4.9.0` should continue to be just fine.

![image](https://github.com/user-attachments/assets/1c180ab4-c599-4767-8e0b-220fa34e6ab6)

**Comment by khskekec** [comment]
Just closed #25 with improved exception message. What is about this ticket?

I just adapted a solution from another PR regarding the clientVersion....

Another hint:

If you try to test stuff you can simply use `npm run test` for this purpose. Your credentials needs to be added to `src/client.test.ts`. This is the easiest way to check for weird api handling.

**Comment by JackDinn** [comment]
This was exactly the solution. Thing was that I had already done the logout and back in on one of my androids but it never presented the EULA, it just re-logged in. However, what I found was that I had to log out of all devices (even my SugarPixel bedroom clock/CGM device) first and then log back in on one android device and it then presented the EULA for me to agree to.

Woohoo. 😊

Next stop (maybe) is to take a look at this NightScout and x-drip, things I have stumbled across on my travels today.

**Comment by khskekec** [comment]
Here is my faked sugarpixel 😊:

![IMG_20240927_202108.jpg](https://github.com/user-attachments/assets/326c487b-1f5d-4e90-b609-2664fd18d011)

![IMG_20240927_202103.jpg](https://github.com/user-attachments/assets/51050eb6-13b4-4c52-87f4-c2fdc4079a55)

![IMG_20240927_202059.jpg](https://github.com/user-attachments/assets/2ce4a63d-cb83-4291-9d92-7344e94597c0)

But less expensive and not that powerful

**Comment by JackDinn** [comment]
Cool, you say "Faked" does that mean you built it yourself? 

Super good job if you did.

**Comment by khskekec** [comment]
Partially ...

The device itself is a prebuild Ulanzi TC001.

The application and the service go get the data and pass it to the device is from me.

It works quite good and just costs around 30€. So much less than the sugarpixel which is too expensive imo.

Kind regards

Selcuk

**Comment by khskekec** [comment]
Here is the Link to the device: https://www.ulanzi.de/products/ulanzi-pixel-smart-uhr-2882?gad_source=1&gclid=Cj0KCQjwr9m3BhDHARIsANut04aygCzea28C8xmv5V8xhAuA-m2ujI6G5oTP4KCvrljGCsdbMg7IaiAaAr1eEALw_wcB

**Comment by JackDinn** [comment]
Nicely done :)

Yeah well, I had no limit on the cost, I just wanted something in my bedroom. It is a bit steep though but their customer service is excellent. I got mine and it had shipping damage to the LED array screen, I spoke to the manager/dev (whatever he is) and told him about it, it was mentioned that I was quite happy with taking the screen out and replacing it as I was (I was, sounds so weird to say "was") an electrical/computer engineer so he sent out a couple of the LED matrices. He was happy to completely replace it. 

Doing fine still (touch wood) 

O thx for the link. Lets hope i never need it :)

**Comment by steinbrueckri** [comment]
@khskekec Can you share the code that how the Ulanzi TC001 Smart Pixel Uhr? @JackDinn maybe you are also interested in this project. https://github.com/sum1els/circuitpy-glucose-display

**Comment by khskekec** [comment]
Hi @steinbrueckri

I think that the code will not help you that much because the way it works is bit different.

Ulanzi is a passive device whichever does not do any connection to the sharing services directly. It just can receive commands what do display over mqtt connections. This is possibles by flashing it without awtrix3, a custom firmware to allow mqtt connections.

The piece which is responsible for connecting to the providers is sitting totally separated. Dexcom, Libre and nightscout are currently supported. This is managed by myself. It is a simple nodejs script so far which gets values and send the commands to mqtt. Ulanzi retrieves it from the mqtt server and shows it then.

You see that some steps are required here and that you need to host stuff yourself.

If you ate interested you can by yourself an ulanzi and we will set it up together.

Actually I am testing the whole arch with some guys to get an understanding of how stable it works. If you want too participate, let me know.

Kind regards 

Selcuk
